[package]
name = "deep-learning-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
anyhow = "1.0"
approx = "0.5"
ndarray = "0.16"
plotters = "0.3"
ndarray-rand = "0.15"
tch = { version = "0.20", features = ["download-libtorch"] }
mylib = { path = "mylib" }
